import type { Site } from "@/lib/schema";

export const demoSite: Site = {
  id: "demo",
  slug: "icai2027",
  version: 1,
  meta: {
    name: "International Conference on Artificial Intelligence 2027",
    acronym: "ICAI 2027",
    tagline: "Advancing machine intelligence for real-world impact",
    type: "international-conference",
    organizer: "Department of Computer Science, Example Institute of Technology",
    deadlines: [],
    venue: { city: "Panipat", country: "India" },
    committee: [],
    speakers: [],
    topics: [],
    fees: [],
    sponsors: [],
    submission: { platform: "cmt", url: "https://cmt3.research.microsoft.com", label: "Submit your paper" },
    contact: { email: "icai2027@example.edu" },
    raw: {},
  },
  theme: {
    id: "emerald-inter",
    label: "Emerald",
    colors: {
      primary: "#0f766e",
      primaryForeground: "#ffffff",
      background: "#ffffff",
      foreground: "#0a0a0a",
      muted: "#f5f7f6",
      mutedForeground: "#5f6b68",
      accent: "#ecfdf5",
      border: "#e3e8e6",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    radius: "md",
    spacing: "normal",
  },
  nav: [
    { label: "About", href: "#about" },
    { label: "Dates", href: "#dates" },
    { label: "Speakers", href: "#speakers" },
    { label: "Register", href: "#fees" },
  ],
  settings: {
    domain: { slug: "icai2027", customDomain: null, domainStatus: "none" },
    seo: { title: "ICAI 2027", description: "International Conference on AI 2027" },
    socialLinks: [],
  },
  pages: [
    {
      id: "home",
      slug: "/",
      title: "Home",
      enabled: true,
      order: 0,
      seo: {},
      layout: {
        root: { props: {} },
        zones: {},
        content: [
          {
            type: "Hero",
            props: {
              id: "hero",
              acronym: "ICAI 2027",
              heading: "International Conference on Artificial Intelligence",
              tagline: "Three days of research, industry practice, and collaboration on applied machine intelligence.",
              dateLine: "12–14 March 2027",
              venueLine: "Panipat, Haryana, India",
              ctaLabel: "Register",
              ctaHref: "#fees",
              secondaryLabel: "Submit your paper",
              secondaryHref: "https://cmt3.research.microsoft.com",
              backgroundImage: "",
            },
          },
          {
            type: "AboutSection",
            props: {
              id: "about",
              eyebrow: "About",
              heading: "About the conference",
              body: "ICAI 2027 brings together researchers, practitioners, and students working across machine learning, computer vision, and applied AI systems.\nThe programme spans peer-reviewed paper sessions, hands-on workshops, and keynote talks from academia and industry.",
              stats: [
                { value: "400+", label: "Expected attendees" },
                { value: "12", label: "Technical tracks" },
                { value: "30+", label: "Institutions" },
              ],
            },
          },
          {
            type: "ImportantDates",
            props: {
              id: "dates",
              eyebrow: "Deadlines",
              heading: "Important dates",
              items: [
                { label: "Call for papers opens", date: "01 Aug 2026", passed: true },
                { label: "Paper submission deadline", date: "15 Nov 2026", note: "Full papers, up to 8 pages" },
                { label: "Notification of acceptance", date: "20 Dec 2026" },
                { label: "Camera-ready submission", date: "15 Jan 2027" },
                { label: "Conference dates", date: "12–14 Mar 2027" },
              ],
            },
          },
          {
            type: "SpeakerGrid",
            props: {
              id: "speakers",
              eyebrow: "Speakers",
              heading: "Keynote speakers",
              columns: "3",
              speakers: [
                { name: "Dr Anita Sharma", title: "Professor of Computer Science", affiliation: "IIT Delhi", photo: "" },
                { name: "Dr Rajesh Kumar", title: "Principal Research Scientist", affiliation: "TCS Research", photo: "" },
                { name: "Dr Meera Iyer", title: "Director, AI Lab", affiliation: "IISc Bangalore", photo: "" },
              ],
            },
          },
          {
            type: "RegistrationFees",
            props: {
              id: "fees",
              eyebrow: "Registration",
              heading: "Registration fees",
              note: "Early-bird rates apply until 15 January 2027. All fees include conference proceedings, lunch, and refreshments.",
              currency: "INR",
              tiers: [
                { category: "Student (early bird)", amount: "3,500", detail: "Valid student ID required at check-in.", featured: true },
                { category: "Academic", amount: "6,500", detail: "Faculty and postdoctoral researchers." },
                { category: "Industry", amount: "9,500", detail: "Corporate and non-academic delegates." },
              ],
              ctaLabel: "Register now",
              ctaHref: "https://cmt3.research.microsoft.com",
            },
          },
          {
            type: "Footer",
            props: {
              id: "footer",
              conferenceName: "ICAI 2027",
              organizer: "Department of Computer Science, Example Institute of Technology",
              email: "icai2027@example.edu",
              phone: "+91 90000 00000",
              address: "Example Institute of Technology, Panipat, Haryana 132103, India",
              links: [
                { label: "Call for papers", href: "#dates" },
                { label: "Registration", href: "#fees" },
                { label: "Contact", href: "mailto:icai2027@example.edu" },
              ],
              copyright: "© 2027 ICAI. All rights reserved.",
            },
          },
        ],
      },
    },
  ],
};